//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Abs.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Driver
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Driver()
        {
            this.Dash = new HashSet<Dash>();
        }
    
        public int DriverId { get; set; }
        public string FullName { get { return Name + " " + Surname; } set { } }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string Phone { get; set; }
        public System.DateTime Age { get; set; }
        public string Adress { get; set; }
        public string Graduate { get; set; }
        public int isAtPool { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Dash> Dash { get; set; }
    }
}
